### ISSUE TITLE
Integration Pt. 3

### ISSUE THREAD

**Issue by Dezainer** [SelflessDev/onc#75]
## Major
- [x] **External Link** in the Partners Modal
- [x] **External Link**(fb or site) for Services Modal
- [x] **CMS ->** External Link(FB), Phone & Celphone **[For Partners]**
- [x] **CMS ->** Church and Minister **[For Partners & Services]**
- [x] **CMS ->** Add Phone and CelPhone **[For Services]**
- [x] Integrate the **services categories** on the **home**
- [ ] Send Form **(Depends on Tests'n'Stuff)**
- [ ] **E-commerce** External Links **(Depends on Them)**
- [x] Partners **Search**
- [x] Fix Services **Search**
- [x] Fix Services on **Footer**
- [x] Mask on the Partner's Phone Showing Wrong... **(404 Error not Found XD)**
- [x] City Selection(Select Input) **Doesn't Work on **Apple Devices**

## Minor
- [x] **'X'** to close on the modals
- [x] Insert in the **Contact** -> **direcao@grupoonc.com.br** & **(46)3524-6512**
- [x] Make **Blue Title Blocks** Smaller
- [x] Insert on **About Page** -> **"Gl 6:10 Então, enquanto temos tempo, façamos bem a todos, mas principalmente aos domésticos da fé."**
- [x] Make the city selection auto-complete scrollable instead of showing 6 items only
- [x] City Selection **Bot Frase** -> Make it italic, put end dot and quotation marks
- [x] Home Services Description Block Bugged on Responsive
- [x] Fix Header-dummy
- [x] Dynamic Background on Partners from Service Type Image (As the Services)
- [x] Name on the partners **(CMS)**
- [ ] Line Break on Description (Partners)**(CMS)**

**Comment by FabiodeBorba** [comment]
As categorias que estão no site não existem no e-commerce
